print("17.", "'Ab' == 'ab' →", 'Ab' == 'ab')
print("18.", "'Harry' < 'harry' →", 'Harry' < 'harry')
print("19.", "not (('B' == 'b') or ('Big' < 'big')) →", not (('B' == 'b') or ("Big" < "big")))
print("20.", "isinstance(32, float) →", isinstance(32, float))
print("21.", "isinstance(32, int) →", isinstance(32, int))
print("22.", "'yt' in 'Python' →", "yt" in "Python")
print("23.", "'knight'.startswith('n') →", "knight".startswith('n'))
print("24.", "True or False →", True or False)
print("25.", "True and False →", True and False)
print("26.", "not True →", not True)
